os:
- linux
# - osx

#dist: trusty

language: php

php:
- "7.1"

script:
# Retrieving, building and testing 'ZNDq'.
- git clone https://github.com/epeios-q37/zndq.git
- pushd zndq
- phpize
- ./configure
- make -j
- php -dextension=modules/zndq.so test.php
- cp modules/zndq.so zndq.xcfg zndq.xlcl ..
# Managing 'eSketch'.
- popd
- make -j
- php -dextension=./zndq.so test.php

# To disable building on tags. Tags are supposed to begin with 'v' and only containing digits.
branches:
  except:
    - /^v[0-9]/
